export const MINIQWACKER_SPELLS = [
  'Flare',
  'Illuminate',
  'Whisper',
  'Eclipse',
  'Shimmer',
  'Enchant',
  'Crescendo',
  'Bewitch',
  'Serenade',
  'Pulse',
  'Harmony',
  'Glisten',
  'Radiant',
  'Evoke',
  'Silhouette',
  'Resonate',
  'Zephyr',
  'Quiver',
  'Luminous',
  'Intrigue',
  'Glimmer',
  'Ethereal',
  'Mystify',
  'Aurora',
  'Rhapsody',
  'Enigma',
  'Sorcery',
  'Reverie',
  'Glow',
  'Incant',
  'Velvet',
  'Umbra',
  'Trance',
  'Vortex',
  'Chime',
  'Ethereal',
  'Talisman',
  'Cauldron',
  'Dazzle',
  'Mystique',
  'Nebula',
  'Orbit',
  'Phantom',
  'Witch',
  'Charm',
  'Shroud',
  'Zeal',
] as readonly string[];

export const QWACKERMASTER_SPELLS = [
  'Lunar Radiance',
  'Mystic Resonance',
  'Celestial Echo',
  'Enchanted Whispers',
  'Astral Harmony',
  'Ethereal Glimmer',
  'Twilight Serenade',
  'Arcane Shimmer',
  'Spectral Resonate',
  'Harmonic Nexus',
  'Luminous Incant',
  'Enigmatic Glow',
  'Crescent Enigma',
  'Divine Zephyr',
  'Cosmic Quiver',
  'Spellbound Silhouette',
  'Magical Chime',
  'Enchanted Zeal',
  'Orbital Aura',
  'Vivid Nebula',
  'Runic Essence',
  'Gleaming Cauldron',
  'Whispering Vortex',
  'Mystical Alchemy',
  'Eclipse Charm',
  "Witch's Veil",
  'Abyssal Rhapsody',
  "Sorcerer's Spell",
  'Aurora Veil',
  'Phantom Nexus',
  'Astral Dazzle',
  'Radiant Mirage',
  "Dreamweaver's Whispers",
  'Zephyr Enchantment',
  'Luminous Veil',
  'Ethereal Dance',
  'Sorcery Mirage',
  'Celestial Serenade',
  'Mystic Zeal',
  'Enchanted Twilight',
  'Enigma Rhapsody',
  'Harmonic Whispers',
  'Nebula Chime',
  'Arcane Harmony',
  'Lunar Resonance',
  'Vivid Trance',
  'Gleaming Aura',
  'Cosmic Dance',
  'Spellbound Mirage',
  'Mystical Shimmer',
] as readonly string[];
